service: serverless-plooral

plugins:
  - serverless-offline
 
custom:
  warmup:
      - production
      - staging

provider:
  name: aws
  runtime: nodejs20.x
  region: sa-east-1
  memorySize: 256
  timeout: 30

functions:
  main:
    handler: dist/main/lambda.handler
    events:
      - schedule:
          rate: cron(*/5 * * * *)